project_name           = "garage"
droplet_size           = "s-1vcpu-3gb" # Example: "s-4vcpu-8gb", "s-2vcpu-4gb"
letsencrypt_env        = "prod" # "staging" or "prod"

# Image Tags - AVOID THESE, use python release.py instead
# postgres_cluster_image_tag = ...
# redis_cluster_image_tag    = ...
# kafka_connect_image_tag    = ...
