version: 2.1

orbs:
  slack: circleci/slack@3.3.0

# yaml basic and advance: https://circleci.com/docs/2.0/writing-yaml/#section=configuration
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: shaungc/terraform-kubectl-image
    working_directory: ~/repo/terraform
    steps:
      - checkout: # retrieves the code from GitHub
          path: ~/repo
      
      # only run blocks below if you updated Dockerfile or terraform script in this repo
      #
      #
      - setup_remote_docker # sets up a remote, isolated environment for each build. This is required before you use any docker command inside a job step.
      - run:
          name: Build Docker image
          command: |
            docker build -f .dockerize/terraform-provisioner/Dockerfile -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1


  exec_terraform:
    docker:
      - image: shaungc/terraform-kubectl-image
    working_directory: /repo/terraform
    steps:
      - run:
          name: Initiate Terraform
          command: |
            chmod +x init-backend-cicd.sh
            sh ./init-backend-cicd.sh
      - run:
          name: Validate Terraform
          command: |
            terraform validate
      # - run:
      #     name: Plan Terraform
      #     command: |
      #       terraform plan -var="letsencrypt_env=prod" -var="app_container_image_tag=latest" -var="appl_tracky_api_image_tag=latest"
      - run:
          name: Test Kubectl
          command: |
            bash my-kubectl.sh version --client


      # only run this block if you want to provision infra here instead of the iriversland2-public circleci.
      #
      #
      # - run:
      #     name: Test Terraform Apply
      #     command: |
      #       terraform apply -var="letsencrypt_env=prod" -var="app_container_image_tag=ed0eb72f35c92a65cc2e39549f0ec883cbf02a27" -auto-approve


      - slack/status:
          mentions: 'here,'
          success_message: "*Build & Test Terraform Complete*\nThe Terraform base image \"shaungc/terraform-kubectl-image\" is ready to be used!"


workflows:
  build-master:
    jobs:
      - build:
        filters:
            branches:
              only: master
      - exec_terraform:
          requires:
            - build