version: 2.1

orbs:
  slack: circleci/slack@3.3.0

# yaml basic and advance: https://circleci.com/docs/2.0/writing-yaml/#section=configuration
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: shaungc/terraform-kubectl-image
    working_directory: ~/repo/tf-kubectl-toolkit
    steps:
      - checkout: # retrieves the code from GitHub
          path: ~/repo
      
      # only run blocks below if you updated Dockerfile or terraform script in this repo
      #
      #
      - setup_remote_docker # sets up a remote, isolated environment for each build. This is required before you use any docker command inside a job step.
      - run:
          name: Build Terraform-Kubectl Toolkit image
          command: |
            docker build -f Dockerfile -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1


  exec_terraform:
    docker:
      - image: shaungc/terraform-kubectl-image
    working_directory: ~/repo/terraform
    steps:
      - checkout: # retrieves the code from GitHub
          path: ~/repo
      - run:
          name: Initiate Terraform Against Cluster
          command: |
            chmod +x init-backend-cicd.sh
            sh ./init-backend-cicd.sh
      - run:
          name: Validate Terraform
          command: |
            terraform validate
      - run:
          name: Plan Terraform
          command: |
            terraform apply -auto-approve \
              -target=local_file.kubeconfig \
              -var="letsencrypt_env=prod" \
              -var="docker_registry_url=https://index.docker.io/v1/" \
              -var="managed_route53_zone_name=shaungc.com." \
              -var="managed_k8_rx_domain=shaungc.com" \
              -var="letsencrypt_env=prod" \
              -var="postgres_cluster_image_tag=latest" \
              -var="redis_cluster_image_tag=latest" \
              -var="kafka_connect_image_tag=latest" \
      - run:
          name: Test Kubectl
          command: |
            bash my-kubectl.sh version --client
            bash my-kubectl.sh get all --all-namespaces
      - slack/status:
          mentions: 'here,'
          success_message: "*Build & Test Terraform Complete*\nThe Terraform base image \"shaungc/terraform-kubectl-image\" is ready to be used!"


workflows:
  build-master:
    jobs:
      - build:
        filters:
            branches:
              only: master
      - exec_terraform:
          requires:
            - build
